manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: personal
      url-base: https://github.com/ask-786
    - name: zampierilucas
      url-base: https://github.com/zampierilucas
  projects:
    - name: zmk
      remote: personal
      revision: fix/no-usb-wakeup-on-battery-report
      import: app/west.yml
  self:
    path: config
